variable "default_folder_id" { //your folder-id
  default = "b1gfl7u3a9ahaamt3ore"
}

variable "default_cloud_id" { //your cloud-id
  default = "b1g3o4minpkuh10pd2rj"
}

variable "default_token" { //your token that should be generated by 'yc iam create-token'
  default = "t1.9euelZqNx8qOms_Lm57Pl5OPm8fKlu3rnpWamouTnceNyZaamc-Uy4-Mj47l9PcfeX9T-e8aeF2k3fT3P1B-U_nvGnhdpM3n9euelZrPlpmek8mPm8iVkM_KkpmKzO_8xeuelZrPlpmek8mPm8iVkM_KkpmKzL3rnpWaz5ydz5qVjcmMjcmPx8_Kxoy164ac0ZaektGQj5qRlpvSjJqNiZqN.O_gYFwoN4f6nlgRN1nRxvUibGjHkVsKgSiY3chEhYr4UJ80Seedh3CTyFhNlXv3LvffcFf5ojm1HjYb7d-_LCw"
}

variable "default_service_account_id" { //your service-account id
  default = "ajem568mqjomnf5o7gqh"
}

variable "default_network_id" { //your network-id
  default = "enp9rm1debn7usfmtlnv"
}

variable "default_zone" { //your default zone that is defined in provider.tf file
  default = "ru-central1-a"
}

variable "YC_VALUE" {
  type        = string
  description = "value for lockbox secret"
}