variable "default_folder_id" { //your folder-id
  default = "b1gfl7u3a9ahaamt3ore"
}

variable "default_cloud_id" { //your cloud-id
  default = "b1g3o4minpkuh10pd2rj"
}

variable "default_token" { //your token that should be generated by 'yc iam create-token'
  default = "t1.9euelZrMzJSezJyYjMyZl5KPlMmKie3rnpWamouTnceNyZaamc-Uy4-Mj47l9Pc1WHlT-e8PPDKv3fT3VS94U_nvDzwyr83n9euelZrLl8yLjc-dzZ7JjJOTyIzJi-_8xeuelZrLl8yLjc-dzZ7JjJOTyIzJi73rnpWaz4nLzZvKnpHMy5SSyZ3Nj5e164ac0ZaektGQj5qRlpvSjJqNiZqN.OBqXvW4GR2yI_wercIlyhrE_kG5tVSL9dQX2-lcP2laOLH2iVMfc6tbdhLdp9Swp1j3nNPFMIlQ-rmHpuRoHBg"
}

variable "default_service_account_id" { //your service-account id
  default = "ajem568mqjomnf5o7gqh"
}

variable "default_network_id" { //your network-id
  default = "enp9rm1debn7usfmtlnv"
}

variable "default_zone" { //your default zone that is defined in provider.tf file
  default = "ru-central1-a"
}

variable "YC_VALUE" {
  type        = string
  description = "value for lockbox secret"
}