variable "default_folder_id" { //your folder-id
  default = "b1gfl7u3a9ahaamt3ore"
}

variable "default_cloud_id" { //your cloud-id
  default = "b1g3o4minpkuh10pd2rj"
}

variable "default_token" { //your token that should be generated by 'yc iam create-token'
  default = "t1.9euelZqWi57ImJuZkJfLmMrMlZXOme3rnpWamouTnceNyZaamc-Uy4-Mj47l8_dnBXBT-e8NXFxr_t3z9wddblP57w1cXGv-zef1656Vms3GysmNm8eUx5iLmoyMms2b7_zF656Vms3GysmNm8eUx5iLmoyMms2bveuelZqNjsaSlZ2TiciOyoyUzp6UyrXrhpzRlp6S0ZCPmpGWm9KMmo2Jmo0.vcL-gE2-VY8L_WDDMgqzHkrMPUvta0JF-BRqtTvLBdi_A-H9FOv6g47bGzei9V8JC2DIwfxYTrWcPWdpszFxDg"
}

variable "default_service_account_id" { //your service-account id
  default = "ajem568mqjomnf5o7gqh"
}

variable "default_network_id" { //your network-id
  default = "enp9rm1debn7usfmtlnv"
}

variable "default_zone" { //your default zone that is defined in provider.tf file
  default = "ru-central1-b"
}

variable "YC_VALUE" {}